### ISSUE TITLE
sort output?

### ISSUE THREAD

**Issue by daurnimator** [leegao/see.lua#5]
It might be nicer if printed tables were sorted by key.

**Comment by leegao** [comment]
I was just thinking about this

**Comment by leegao** [comment]
![Imgur](http://i.imgur.com/AKMifz2.png)

One thing though. The current layout engine attempts to greedily pack the entries so we don't get awkward breaks in the layout when we have excessively long entries to consider. This means that the resulting layout isn't completely sorted, since some entries are shuffled to around a little bit in order to pack in previously unoccupied slots.

For example, in the above screenshot, `._VERSION` ought to come before `.arg`, but since `._VERSION` wouldn't fit the end of the row, `see.lua` decided to move the `.arg` up instead. This might get a little confusing, but in most cases, it should be nearly sorted with out-of-order items nearby. I might change this behavior in the future, but it seems like a sane tradeoff for now.

**Comment by daurnimator** [comment]
Solved with ed1650cbba32a1ae8d897831a65b97e214ffde6d
